#include "console_utils.hpp"

// No need for byte overrides since we've disabled std::byte completely with _HAS_STD_BYTE=0
#ifdef _WIN32
#include <windows.h>
#endif

// Define color constants
const WORD BRIGHT_GREEN_MAIN = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD BRIGHT_BLUE_MAIN = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD BRIGHT_RED_MAIN = FOREGROUND_RED | FOREGROUND_INTENSITY;
const WORD BRIGHT_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY; 
const WORD BRIGHT_VIOLET_MAIN = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY; 
const WORD BRIGHT_PURPLE_MAIN = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY; 
const WORD DEFAULT_COLOR_MAIN = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE; 

// Define the console handle
HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
